spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

spring.flyway.enabled=false
management.health.elasticsearch.enabled=false
management.health.rabbit.enabled=false

debug=false
logging.level.root=INFO
